ENH: Improve Sun CC support
Patch from Hady Zalek:

- Changed find_flags to no longer use truss to find include directories
- Changed find_flags and README to make it more generic for any CC
  version
- Changed find_flags and adapt script to use CXXFLAGS in for possible
  use of '-library=stlport4'
- Moved adapt_headers.sh into 5.8 since it's really version specific
- Split off Cstd related changes into a separate patch
- Added patching for standard includes under Solaris 5.10
- Fixed compilation error under Solaris 5.8 where stdint.h is missing
- Fixed static gstdint.h to use config.h constants to determine whether
  to include stdint.h or inttypes.h
- Added SunOS version-specific patching mechanims

diff --git a/GCC_XML/Support/Sun/find_flags b/GCC_XML/Support/Sun/find_flags
--- a/GCC_XML/Support/Sun/find_flags
+++ b/GCC_XML/Support/Sun/find_flags
@@ -15,7 +15,8 @@
 #     PURPOSE.  See the above copyright notices for more information.
 #
 #=============================================================================
-# Find the CC executable name.
+
+# Find the compiler executable name.
 if test "x$1" = "x" ; then
   if test "x${CXX}" = "x" ; then
     CXX=CC
@@ -26,44 +27,25 @@ else
   CXXFLAGS="$@"
 fi
 
-GCCXML_PID="$$"
-cat > "/tmp/gccxml_identify_compiler_args$GCCXML_PID.cc" <<!
-#include <>
-!
+# Find the compiler version
+CXX_VERSION=`${CXX} -V 2>&1 | awk '{print $4}'`
+[ -z "${CXX_VERSION}" ] && echo "Could not find compiler version" && exit 1
 
-# Find the macro definition options.
-MACROS=`${CXX} /tmp/gccxml_identify_compiler_args$GCCXML_PID.cc -E -xdumpmacros=defs 2>&1 |
-       awk '{ if ($1 ~ /#define/) printf("-D%s=%s %s %s ",$2,$3,$4,$5) }'
-       ` 
-MACROS="-D__cplusplus=199711L -D__STDC__ -D_REENTRANT $MACROS"
+# Compute the script dir
+SCRIPT_DIR=`dirname $0`
+if test "x$SCRIPT_DIR" = "x" ; then SCRIPT_DIR="." ; fi
+SCRIPT_DIR=`cd "$SCRIPT_DIR" ; pwd`
 
-# Find the include path options.
-#todo test for truss
-INCLUDES=`truss -f -t openat ${CXX} -E /tmp/gccxml_identify_compiler_args$GCCXML_PID.cc 2>&1 |
-         awk '{if ($3 ~ /\"[A-Za-z0-9_\/.-]+\",/ && $3 !~ /tmp/)
-                 if (tempString!=substr($3,2,length($3)-3))
-                 {
-                    tempString=substr($3,2,length($3)-3);
-                    printf("-I%s ",tempString)
-                 }
-               }'`
+# Compute the version-specific support dir
+CXX_SUPPORT_DIR="$SCRIPT_DIR/$CXX_VERSION"
 
-#cleanup
-rm -rf "/tmp/gccxml_identify_compiler_args$GCCXML_PID.cc"
-
-# The support headers are located where this script is.
-SELFPATH=`echo $0 | sed -n '/\//{s/\/find_flags//;p;}'`
-if test "x$SELFPATH" = "x" ; then SELFPATH="." ; fi
-SELFPATH=`cd "$SELFPATH" ; pwd`
-
-# Find CC version
-CC_VERSION=`${CXX} -V 2>&1 | awk '{print $4}'`
-
-# Use hacked headers for CC 5.8
-if [ $CC_VERSION = 5.8 ]; then
-  INCLUDES="-iwrapper\"$SELFPATH/5.8\" $INCLUDES"
+# Use the version-specific find_flags if available
+if [ -f "$CXX_SUPPORT_DIR/find_flags" ]
+then
+  . "$CXX_SUPPORT_DIR/find_flags"
+else
+  . "$SCRIPT_DIR/find_flags_common"
 fi
  
-# Format and print out the options.
-OPTIONS="$MACROS $INCLUDES $SPECIAL"
+# Print out the options
 echo $OPTIONS
